### ISSUE TITLE
How do I support a controller method to allow an unauthenticated request in your example?

### ISSUE THREAD

**Issue by ghost** [bobbywarner/grails3-oauth2-api#2]
Without success, I've tried annotating a controller action with

```
@Secured("IS_AUTHENTICATED_ANONYMOUSLY")
```

or 

```
@RolesAllowed("IS_AUTHENTICATED_ANONYMOUSLY")
```

Thanks in advanced.

**Comment by bobbywarner** [comment]
You can exclude certain URLs from being secured here: https://github.com/bobbywarner/grails3-oauth2-api/blob/master/grails-app/init/demo/OAuth2ServerConfiguration.groovy#L44
