### ISSUE TITLE
Is it possible to return access and refresh token in the RegisterController action?

### ISSUE THREAD

**Issue by ghost** [bobbywarner/grails3-oauth2-api#3]
@bobbywarner 

In your example the register controller action returns the user first name, last name etc 

Is it possible to return an OAuthToken (with access and refresh token) for the user who was created in that action. 

Thanks in advanced

**Comment by bobbywarner** [comment]
@sergiodelamoshoptimix Yup, you can use the [DefaultTokenServices](http://docs.spring.io/spring-security/oauth/apidocs/org/springframework/security/oauth2/provider/token/DefaultTokenServices.html) class to do this.

You'll want inject the bean like this (`DefaultTokenServices` implements the `ResourceServerTokenServices` interface):

```
@Autowired
ResourceServerTokenServices consumerTokenServices
```
